
SET PROJECT_SOLUTION_NAME=SimilaritySearchExample

SET DATABASE_NAME=ResourceProfilerDb
SET DATABASE_USER=sa
SET DATABASE_PASSWORD=S1m1l@1tyS3@rch

SET PROJECT_ASSEMBLY=%PROJECT_SOLUTION_NAME%.Web
SET PROJECT_SOLUTION=%PROJECT_SOLUTION_NAME%.sln
SET DATALOADER_ASSEMBLY=%PROJECT_SOLUTION_NAME%.Dataloader
SET DATA_PROJECT=%PROJECT_SOLUTION_NAME%.DB
SET DATA_PROJECT_ASSEMBLY=%PROJECT_SOLUTION_NAME%.Persistence


SET DATABASE_CONNECTION=Server=127.0.0.1;Database=%DATABASE_NAME%;User=%DATABASE_USER%;Password=%DATABASE_PASSWORD%;TrustServerCertificate=True;
SET DATALOADER_COMMAND=dotnet run --configuration Release --project %DATALOADER_ASSEMBLY% --
